version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "3002:6379"
    expose:
      - 6379
    restart:
      always
  
  webapp:
    build: .
    ports:
    - 3000:3000
    - 3001:3001
    expose: 
      - 3000 
      - 3001
networks:
  my-net:
    driver: bridge
